### ISSUE TITLE
Support Course Cert Signatory records in Credentials IDA

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/credentials#1794]
- [ ] https://github.com/openedx/credentials/issues/1764
- [ ] https://github.com/openedx/credentials/issues/1765
- [ ] https://github.com/openedx/credentials/issues/1766

**Comment by hurtstotouchfire** [comment]
FYI @cdeery

**Comment by hurtstotouchfire** [comment]
@e0d Do we have a timeline for this? Also is that spreadsheet you sent a public doc? If so I can add that to the description here. A wiki project page link might be a better option though.

**Comment by deborahgu** [comment]
it's my belief that this epic and its associated tickets are no longer happening, is that correct? That is to say, the credentials IDA is _not_ the host of the LMS web certificates, and it is not going to become that host,  and  it should not be considered a blocker to any future deprecation of the old mongo store that has not been completed.

 Could interested parties tell me if I am mistaken about that anyway? Otherwise I will close this epic and the associated tickets.

cc: @justinhynes @GlugovGrGlib
